#!/bin/sh 
export LM_LICENSE_FILE=7321@eclipse-lic-no.statoil.no
export F_UFMTENDIAN=big
export ARCH=`uname -m`
cd /project/eor/user/liuming/opm/opm-sample/data/simple_model/ECL_OUTPUT
/bin/rm -f ECL.CFG
/bin/cp /prog/ecl/grid/macros/CONFIG.ECL ./ECL.CFG 2>> SIMPLE.ERR
executable=/prog/ecl/grid/2012.2/bin/linux_x86_64/eclipse.exe
$executable <<END 
SIMPLE
SIMPLE
30000000
30000000
$executable
END
mv -f /project/eor/user/liuming/opm/opm-sample/data/simple_model/ECL_OUTPUT/SIMPLE.job /project/eor/user/liuming/opm/opm-sample/data/simple_model/ECL_OUTPUT/SIMPLE.job.done
