PVDO      -- pvt for live oil
-- Pressure     Bo       viscosity 
      300      1.089       1.00 
      800      1.081       1.00 
     2900      1.050       1.00      
     4000      1.034       1.00 
/

PVTW
-- Pressure     Bw    compressibility  viscosity  viscosibility
     2900      1.02      6.89E-06         0.3	      0.0 
/

ROCK       
-- Pressure    compressibility
     2900         1.03E-6  
/

DENSITY  
-- oil   water   gas @surface(lbm/scf)
   53.0  64.00   0.062428 
/
